import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-[100dvh] overflow-hidden antialiased`}
    >
      <body className="h-full flex flex-col overflow-y-auto">
        {children}
        <div className="fixed bottom-2 right-2 z-[9999] pointer-events-none opacity-60">
          <span className="text-[10px] font-mono text-slate-800 bg-white/70 px-1.5 py-0.5 rounded backdrop-blur-sm border border-slate-200/50 drop-shadow-sm">
            Dev by Sidang Cikampek
          </span>
        </div>
      </body>
    </html>
  );
}
